### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by XDaast** [netquik/CnCTA-SoO-SCRIPT-PACK#2]
This script doesn't work for some reason after 19.5. I can't figure it out. Got any ideas?

**Comment by XDaast** [comment]
It is the chat helper script.

**Comment by netquik** [comment]
xdaast what does not work? i'm using it and coords and other automatics are
working .. in messages.. in chat you have to put a space after to have text
modified.. i changed this in last release because the way chat message is
sent has changed and can't figure out how to change input before sending

Il giorno mar 25 feb 2020 alle ore 00:10 XDaast <notifications@github.com>
ha scritto:

**Comment by netquik** [comment]
also i receive no errors about the script in console

Il giorno mar 25 feb 2020 alle ore 00:16 netquik <netquik@gmail.com> ha
scritto:

**Comment by XDaast** [comment]
Hey man. Strange… mine does nothing. Perhaps I have a script interfering. When I put in in a url or coord it does not make it a link.

**Comment by netquik** [comment]
in chat or message?
what are you loading apart from the cript included ? i just tested on my
side and all seem to work..
any errors in console?

Il giorno mar 25 feb 2020 alle ore 00:20 XDaast <notifications@github.com>
ha scritto:

**Comment by netquik** [comment]
are you loading it by greasemonky or extension?
maybe is inclusion problem.. most scripts you know are tested by extension
loading not individually

Il giorno mar 25 feb 2020 alle ore 00:22 netquik <netquik@gmail.com> ha
scritto:

**Comment by XDaast** [comment]
Well, it works if I disable everything… very strange! I’ll let you know if I find out what my issue is. Thanks for getting back to me!

**Comment by XDaast** [comment]
I have gotten it to work with everything else disabled... I'll let you know if I find out what is causing my problem.

**Comment by netquik** [comment]
thanks to you.. yes i restested.. probably something interfering
let me know mate

Il giorno mar 25 feb 2020 alle ore 00:24 netquik <netquik@gmail.com> ha
scritto:
