### ISSUE TITLE
"Plan move base" problem on other players bases (TA_TheMovement.user.js ) Tib45 -patch 20.3

### ISSUE THREAD

**Issue by DrLove73** [netquik/CnCTA-SoO-SCRIPT-PACK#3]
Hi.
On world Tiberium 45 there was an update/patch 20.3 yesterday that increased bonuses for 250% for this world among other things. Here is total list: https://www.ea.com/games/command-and-conquer/command-and-conquer-tiberium-alliances/news/20-3-maintenance-patch-notes-sep-21
Now when I click on base of some other player, and click on "Plan move base" button, scripts starts to roll the "darkness" that keeps visible only tiles where that base can jump, but stops around 2-3 seconds after mouse is moved and entire screen/map is frozen. Moving mouse moves bubble with range and coords info with it the mouse, but it is stuck on last active position, does not update any more. Pressing ESC does not help.
I tried with only that option/script active and with all other scripts in a script pack disabled, and it is the same.
Plan moving your own base works without issues. So does Plan ruin and Plan remove and looks like all other buttons work as well.

**Comment by netquik** [comment]
Hi mate I will into it asap


Il mar 22 set 2020, 09:52 Ljubomir Ljubojevic <notifications@github.com> ha
scritto:

**Comment by netquik** [comment]
unfortunately it seems i can't start a new game in that world for testing.
Anyway i tested themovement on other world updated to 20.3 and it seems to
work as expected

Il giorno mar 22 set 2020 alle ore 10:32 netquik <netquik@gmail.com> ha
scritto:

**Comment by netquik** [comment]
ok looking better on it.. yes there i a problem on plan base... will follow
up

Il giorno mar 22 set 2020 alle ore 10:48 netquik <netquik@gmail.com> ha
scritto:

**Comment by netquik** [comment]
https://forums.ea.com/en/commandandconquer/discussion/comment/2156285/#Comment_2156285

Il giorno mar 22 set 2020 alle ore 10:52 netquik <netquik@gmail.com> ha
scritto:

**Comment by netquik** [comment]
Ok i think i have a fix for the problem.. took me 2 days.
I will post asap the new version on the forum to test (as standalone script)
after that i will publish new pack version

thanks

Il giorno mar 22 set 2020 alle ore 15:51 netquik <netquik@gmail.com> ha
scritto:

**Comment by DrLove73** [comment]
I tested this one y copying js into Tampermonkey and it works now. Thanks.
