### ISSUE TITLE
CnC Tiberium Alliances POIs Analyser 2.0.3 does not properly show increased +250% bonuses

### ISSUE THREAD

**Issue by DrLove73** [netquik/CnCTA-SoO-SCRIPT-PACK#4]
Hi.
Alliances POIs Analyser (When you click Aliance menu->Alilance POI) needs to be updated to reflect increased POI bonuses (+250%) that EA granted with new update to World 45 (I do not know about other worlds).

What I did in my spreadsheet for POI calculations, and what I suggest to you, is to detect world with granted bonus increase and jut multiply Total Bonus 2,5 times.
If you can not detect which world is it, or as a stopgap measure, adding "Boosted Total Bonus" bellow Total Bonus would sufice.

**Comment by netquik** [comment]
Ok thanks I will try to look into this issue


Il dom 27 set 2020, 20:00 Ljubomir Ljubojevic <notifications@github.com> ha
scritto:

**Comment by netquik** [comment]
The problem is i have no access to World 45

Il giorno dom 27 set 2020 alle ore 20:03 netquik <netquik@gmail.com> ha
scritto:

**Comment by DrLove73** [comment]
First, I must apologize about mis-naming the world, It is Tiberium 45.

I can attack the image of my alliance bonuses from Tiberium 45, but I have Analyzed numbers game presents and POI Analyzer presents (in Simulator) and the difference to other worlds is that Score to Bonus table is multiplied by 250%, or 2,5 times.

Proper way to fix this would be to create a separate "Tier" table where:
Tier 28 is still 25,000,000, but Bonus is no longer 1,850,000 but 4,625,000, and 
Tier 25 is still 7,000,000, but Bonus is no longer 72% but 180% 

But as far as I am concern, all I need is to have "Bonus" and "Total Bonus" in Simulator to show numbers multiplied with 2,5.

**Comment by netquik** [comment]
HI
can you check what is the result of this command
ClientLib.Data.MainData.GetInstance().get_Server().get_POIGlobalBonusFactor()

in that world


Il giorno mar 29 set 2020 alle ore 07:54 Ljubomir Ljubojevic <
notifications@github.com> ha scritto:

**Comment by DrLove73** [comment]
Hi. I am a programmer for many years, but I have not dealt with Javascript.
Can you create simple script that would show me result of that command somehow, in a popup window maybe?
Or if you can explain how to run that command in Firefox (I have tampermonkey) I will.

**Comment by DrLove73** [comment]
OK, I figured it out, ran it in Web Developer. 
Result is 2.5

**Comment by netquik** [comment]
Good! That is our variable now we need to know what to modify ... Can you
via screenshots give me all mod you believe useful ? Thanks mate

Il mar 29 set 2020, 18:38 Ljubomir Ljubojevic <notifications@github.com> ha
scritto:

**Comment by DrLove73** [comment]
Here are screenshots (2 parts because I activate some hidden ones):
https://prnt.sc/uq6tdj
https://prnt.sc/uq6thy

**Comment by netquik** [comment]
oh well yes.. but i was speaking about poi analyser... we found the
variable we need to see if world has boost bonus.
now id you want to patch it i need to know how.
i can try multiply bonus.. but i think we need  more wide patch to
reflect word boost bonus

Il giorno mar 29 set 2020 alle ore 23:16 Ljubomir Ljubojevic <
notifications@github.com> ha scritto:

**Comment by DrLove73** [comment]
Sorry, misunderstood you.

I was looking at the code you have in this git repository and I see TA_leoStats.user.js applies POIGlobalBonusFactor variable in some way.
So same should be applied to https://greasyfork.org/en/scripts/1934-c-c-tiberium-alliances-pois-analyser/code code.

Somewhere around line 87 you should get the factor into variable, and then around line 100 you need to multiply bonus array item with POIGlobalBonusFactor before it is added to array. That should solve the issue.

**Comment by netquik** [comment]
ok yes so only bonus in tiers? the other tools? the graph? should i modify
also that?
i asked you because i actually can't test or use the script with real data

Il giorno mer 30 set 2020 alle ore 07:56 Ljubomir Ljubojevic <
notifications@github.com> ha scritto:

**Comment by netquik** [comment]
hi mate can you test this using greasemonkey as standalone script?
(you have to disable it in my pack first)

https://github.com/netquik/CnCTA-SoO-SCRIPT-PACK/raw/Testing/TA_POIs_Analyser.user.js

Il giorno mer 30 set 2020 alle ore 11:00 netquik <netquik@gmail.com> ha
scritto:

**Comment by netquik** [comment]
let me know if it world as intended
i think we should also notify in some way that the world has GlobalBonus > 1
i think like changing Bonus label in someway

Il giorno mer 30 set 2020 alle ore 11:32 netquik <netquik@gmail.com> ha
scritto:

**Comment by netquik** [comment]
update that added labels.. let me know

Il giorno mer 30 set 2020 alle ore 11:33 netquik <netquik@gmail.com> ha
scritto:

**Comment by netquik** [comment]
[image: image.png]

Il giorno mer 30 set 2020 alle ore 12:21 netquik <netquik@gmail.com> ha
scritto:

**Comment by DrLove73** [comment]
I am at work, will try in 5h.

**Comment by netquik** [comment]
No problem mate. Thanks!

Il giorno mer 30 set 2020 alle ore 12:23 Ljubomir Ljubojevic <
notifications@github.com> ha scritto:

**Comment by DrLove73** [comment]
It works! In all parts of the script.
Old Analyzer: https://prnt.sc/uqiqln
New Analyzer: https://prnt.sc/uqirig (I have 3 accounts so I tested on one and compared on the other).

**Comment by netquik** [comment]
Glad to hear it!
now please check because i uploaded another version with label mod that i
can't see in you screenshot
i didn't change version number so you have to load it manually

Il giorno mer 30 set 2020 alle ore 13:11 Ljubomir Ljubojevic <
notifications@github.com> ha scritto:

**Comment by DrLove73** [comment]
I used only link you gave me I just copied script again into Tampermonkey. 
If updated script is not same as your last link/file, then you have to post a link of last version.

**Comment by netquik** [comment]
the link is the same always in testing branch

in the script you should see Bonus +250% labels

Il giorno mer 30 set 2020 alle ore 15:55 Ljubomir Ljubojevic <
notifications@github.com> ha scritto:

**Comment by DrLove73** [comment]
Ahh, ok, I see them now. I did not know what to look for.
"Bonus +250%" is written in both Statistics, Simulator and Tier's as column header.

**Comment by netquik** [comment]
Good!


Il mer 30 set 2020, 22:24 Ljubomir Ljubojevic <notifications@github.com> ha
scritto:

**Comment by netquik** [comment]
That's world  . Ok firestorm 14 gives +200.. ok.. anything else fixable
here? I love blindly fix things!



Il mer 30 set 2020, 22:48 netquik <netquik@gmail.com> ha scritto:

**Comment by DrLove73** [comment]
Only "Paste Coords" let to be fixed and you can compile a new script pack addon :-)

**Comment by netquik** [comment]
I have a fixed version to test.. uploading in testing branch asap... But I
need to verify something else that should take 2 days ... Yes I will
publish new pack just after

Il mer 30 set 2020, 22:54 Ljubomir Ljubojevic <notifications@github.com> ha
scritto:

**Comment by netquik** [comment]
https://github.com/netquik/CnCTA-SoO-SCRIPT-PACK/raw/Testing/TA_MovableMenuOverlay.user.js

FIX TRY 1
any feedback useful thanks

Il giorno mer 30 set 2020 alle ore 23:37 netquik <netquik@gmail.com> ha
scritto:

**Comment by DrLove73** [comment]
I tested it, and so far every time coords were posted correctly in chat, even if list of messages was open. Only when window to write/reply message is open were coords sent to that window. As soon as mail was discarded, coords wer posted back to chat.
Tumbs up!
Thanks.

**Comment by netquik** [comment]
Good! Thanks, So i will verify just one thing and go to master

Il giorno gio 1 ott 2020 alle ore 08:32 Ljubomir Ljubojevic <
notifications@github.com> ha scritto:

**Comment by DrLove73** [comment]
There is anothor place where POIGlobalBonusFactor needs to be applied.
I decided to fill my spreadsheet with some Scores and Bonuses that were missing in highest level POI, and I see that in Tiers table both Bonuses and Percentage columns also need to be multiplied with POIGlobalBonusFactor.

**Comment by DrLove73** [comment]
There is another thing.
When in Tiers column rows reach tier 39, all Percentages bellow are 100%. It looks like code needs to allow percentages above 100.

**Comment by netquik** [comment]
well don't know how actually works
but seems that multipliers for ranks 41+ is 0%

Il giorno gio 1 ott 2020 alle ore 12:22 Ljubomir Ljubojevic <
notifications@github.com> ha scritto:

**Comment by DrLove73** [comment]
OK, that might be correct, I have no way of knowing. If I find out I will let you know.

So only thing for now to fix is multiply POIGlobalBonusFactor for Tiers table.

**Comment by netquik** [comment]
[image: image.png]
Is it not correct?

Il giorno gio 1 ott 2020 alle ore 14:43 Ljubomir Ljubojevic <
notifications@github.com> ha scritto:

**Comment by DrLove73** [comment]
I do not see any image. Can you put a link to https://prnt.sc ?

**Comment by netquik** [comment]
http://prntscr.com/ure79d


Il giorno gio 1 ott 2020 alle ore 16:25 Ljubomir Ljubojevic <
notifications@github.com> ha scritto:

**Comment by DrLove73** [comment]
> There is another thing.
> When in Tiers column rows reach tier 39, all Percentages bellow are 100%. It looks like code needs to allow percentages above 100.

I was wrong about this.
I found some time to properly look at things.
As for percentage bonuses, they stop at 100% (250% on T45), there is no increase while Tib/Xtal/power bonuses continue to increase. I manually checked on one of the strongest alliances where they maxed out to +250% on several different Tiers, so that is ok.

**Comment by netquik** [comment]
Ok 👌

Il ven 2 ott 2020, 09:59 Ljubomir Ljubojevic <notifications@github.com> ha
scritto:

**Comment by DrLove73** [comment]
Tiers table also looks good. I might have looked at old version on other account (I play with 3 accounts at the same time, switching between them).
Here is screenshot of same tiers on T45 with fixed version you posted: https://prnt.sc/urq75t

**Comment by netquik** [comment]
good the only thing i can do is settings 0% for higher ranks multiplier..
but as you can see in that table (multiplier) after 40 is all 0%.
You can check multiplier directly for each rank using internal funcion;
ClientLib.Base.PointOfInterestTypes.GetBoostModifierByRank(x)
where x is rank level

Il giorno ven 2 ott 2020 alle ore 12:53 Ljubomir Ljubojevic <
notifications@github.com> ha scritto:

**Comment by netquik** [comment]
now mate i did another version always in testing.
Here i modified the script because was my knowledge that there were
problems with alliance tabs not showing.
let me know

Il giorno ven 2 ott 2020 alle ore 13:20 netquik <netquik@gmail.com> ha
scritto:

**Comment by DrLove73** [comment]
I have tested the latest version and everything works.
I think you can publish new version of the add-on.
And thanks for creating and maintaining it.

**Comment by netquik** [comment]
Great! thanks

Il giorno sab 3 ott 2020 alle ore 23:57 Ljubomir Ljubojevic <
notifications@github.com> ha scritto:
