### ISSUE TITLE
"Paste Coords" button problem

### ISSUE THREAD

**Issue by DrLove73** [netquik/CnCTA-SoO-SCRIPT-PACK#5]
There is a nagging problem with "Paste Coords" button.
When I first login, Paste Coords pastes coords into Chat. 
But the moment I send a message, Paste Button stops working for chat. I think there is a trigger to redirect coords to message when message window is detected, but that variable is never reset before every click on the button, so after first message Paste Coords sends coords only to message window, never again to chat, no matter is message window is open or not.

**Comment by netquik** [comment]
Hi! yes seems there is a problem when you close message or cancel without discarding the message.
If you open new message and discard all return to work.
I think that closing a void message leave an instance of message.
I will look into it asap

**Comment by netquik** [comment]
@DrLove73 Are you using MovebleMenuOverlay Script?

**Comment by DrLove73** [comment]
Yes, it is turned on.

**Comment by netquik** [comment]
Ok the problem should be my script.

Il giorno mer 30 set 2020 alle ore 17:19 Ljubomir Ljubojevic <
notifications@github.com> ha scritto:

**Comment by netquik** [comment]
Should be solved in last version.
