### ISSUE TITLE
CnCTAOpt is broken in the lastest release

### ISSUE THREAD

**Issue by nimrod46** [netquik/CnCTA-SoO-SCRIPT-PACK#9]
Hi, the latest version `1.5.5` breaks the CnCTAOpt button, it doesn't show up even though you choose the right option:

![image](https://user-images.githubusercontent.com/11810541/109079725-060ea980-7708-11eb-8dfc-33f649325d54.png)

Missing the CnCTAOpt button:
![image](https://user-images.githubusercontent.com/11810541/109079800-22124b00-7708-11eb-9257-39eac725b432.png)

**Comment by netquik** [comment]
yes.. is 3 weeks i 've done 1.5.6... but google ii slow reviewing .. i try
public 1.5.6 right now

Il giorno gio 25 feb 2021 alle ore 00:24 nimrod46 <notifications@github.com>
ha scritto:

**Comment by netquik** [comment]
you can finf 1.5.6 on firefox opera and edge meanwhile

Il giorno gio 25 feb 2021 alle ore 01:50 netquik <netquik@gmail.com> ha
scritto:

**Comment by netquik** [comment]
if you have problems with 1.5.6 let me know here thanks

**Comment by nimrod46** [comment]
Oh I see, then it's not the latest release, I remember Firefox released ver `1.5.5` about a month ago, Google surely are taking their time.
Thanks for your hard work on this script!
I will keep this issue open as more users probably will start receiving ver `1.5.5`

**Comment by netquik** [comment]
yes. Thanks. 1.5.6 is on review now. I hope it finds the way soon to Chrome
Store.

Il giorno gio 25 feb 2021 alle ore 15:23 nimrod46 <notifications@github.com>
ha scritto:

**Comment by netquik** [comment]
meanwhile you can use that script loading it in Tampermonkey or
if don' want to use it you can "select all" the below code and paste in chrome console (F12) after game loaded and RETURN
https://github.com/netquik/CnCTA-SoO-SCRIPT-PACK/blob/master/TA_CnCTAOpt_Link_Button.user.js

**Comment by ZeroTolerance13** [comment]
ReferenceError: unsafeWindow is not defined
    at TA_CnCTAOpt_Link_Button.user.js:35

after that it breaks at gmlog

**Comment by netquik** [comment]
Yes @ZeroTolerance13 that is the mayor problem in the original version of the author. We discussed on his github and fixed all problems. Unfortunately my fault was trying publishing on Chrome Store too early (for other problems, hoping it could review the code in some days) but it took 3 weeks for 1.5.5 (with old code included) to be published. As I said 1.5.6 includes fixed code and is already available since a week on Mozialla add-ons, Opera add-ons, and aslo Microsoft Edge extensions.

**Comment by nimrod46** [comment]
The new version came out which fixed the problem, thanks!
